export const doctors = [
    {
        id: 1,
        experience: 12,
        name: "John Doe",
        specialization: "Cardiologist",
        img: "https://hips.hearstapps.com/hmg-prod/images/portrait-of-a-happy-young-doctor-in-his-clinic-royalty-free-image-1661432441.jpg",
    },
    {
        id: 2,
        experience: 7,
        name: "Smith Orily",
        specialization: "Dermatologist",
        img: "https://images.theconversation.com/files/304957/original/file-20191203-66986-im7o5.jpg?ixlib=rb-4.1.0&q=45&auto=format&w=926&fit=clip",
    },
    {
        id: 3,
        experience: 10,
        name: "Axel Chinua hesk",
        specialization: "Cardiologist",
        img: "https://hips.hearstapps.com/hmg-prod/images/portrait-of-a-happy-young-doctor-in-his-clinic-royalty-free-image-1661432441.jpg",
    },
    {
        id: 4,
        experience: 5,
        name: "Jennifer Gray",
        specialization: "Psychatrist",
        img: "https://images.theconversation.com/files/304957/original/file-20191203-66986-im7o5.jpg?ixlib=rb-4.1.0&q=45&auto=format&w=926&fit=clip",
    },
    {
        id: 5,
        experience: 9,
        name: "Welk Snipls",
        specialization: "Cardiologist",
        img: "https://hips.hearstapps.com/hmg-prod/images/portrait-of-a-happy-young-doctor-in-his-clinic-royalty-free-image-1661432441.jpg",
    },
    {
        id: 6,
        experience: 9,
        name: "Welk Snipls",
        specialization: "Cardiologist",
        img: "https://www.scripps.org/sparkle-assets/images/primary_care_physician_1200x750-163ed71c4c87820817101e72ab78901d.jpg",
    },
    {
        id: 7,
        experience: 9,
        name: "Welk Snipls",
        specialization: "Cardiologist",
        img: "https://hips.hearstapps.com/hmg-prod/images/portrait-of-a-happy-young-doctor-in-his-clinic-royalty-free-image-1661432441.jpg",
    },
    {
        id: 8,
        experience: 9,
        name: "Welk Snipls",
        specialization: "Cardiologist",
        img: "https://www.scripps.org/sparkle-assets/images/primary_care_physician_1200x750-163ed71c4c87820817101e72ab78901d.jpg",
    },
];
